<a href="https://colab.research.google.com/github/Reben80/LinearAlgebra_DataScience/blob/main/Finding_RREF_of_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## RREF using Python & NumPy

Step 1: Installation

First, ensure you have NumPy and sympy imported.

In [ ]:
import numpy as np
from sympy import Matrix
import sympy

In [ ]:

def math264_rref(matrix):
    # Convert the input matrix to a SymPy Matrix object
    sympy_matrix = Matrix(matrix)

    # Calculate the Reduced Row Echelon Form (RREF) using SymPy.
    # The rref() method returns two values: the RREF matrix and the pivot columns.
    # We're only interested in the RREF matrix, so we ignore the second return value using "_".
    rref_matrix, _ = sympy_matrix.rref()

    # Convert the RREF matrix from a SymPy Matrix back to a NumPy array.
    # Additionally, we ensure all values in the matrix are floats.
    return np.array(rref_matrix).astype(float)


# Creating a matrix using random

In [ ]:
# Random matrix with values between 0 and 1
matrix_rand = np.random.rand(3, 4)
print("Matrix with values between 0 and 1:\n", matrix_rand)

# Random integer matrix with values between 0 and 9
matrix_randint = np.random.randint(0, 10, (3, 4))
print("\nMatrix with random integers between 0 and 9:\n", matrix_randint)

Matrix with values between 0 and 1:
 [[0.2738921  0.76845171 0.85190681 0.87020363]
 [0.14170222 0.21383497 0.33579431 0.6871175 ]
 [0.58880795 0.89108096 0.3906816  0.56077003]]

Matrix with random integers between 0 and 9:
 [[9 3 5 4]
 [6 2 7 9]
 [6 9 8 8]]


In [ ]:
R=[[1,0,-1,-3,-3],[0,1,5,13,12],[1,-1,-5,-13,-12]]
RR=math264_rref(Matrix(np.array(R)))
print(RR)


[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0. -2. -3.]
 [ 0.  0.  1.  3.  3.]]


In [ ]:
# Define the Span function
def math264_Span(A):
    RREF_A = math264_rref(np.array(A))

    # Count the number of pivot columns (non-zero rows in RREF)
    pivot_count = 0
    for row in RREF_A:
        if not all(val == 0 for val in row):
            pivot_count += 1

    # Determine if A spans Rn
    _, n = A.shape
    if pivot_count == n:
        return True, f"The matrix A spans R^{n}"
    else:
        return False, f"The matrix A does not span R^{n}. It only spans R^{pivot_count}"

# Test the function
A = np.array([[1, 2, 3], [2, 4, 6], [0, 0, 1]])
result, message = math264_Span(A)
result, message

(False, 'The matrix A does not span R^3. It only spans R^2')